/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as UserRegisterImport } from './routes/userRegister'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as ReportImport } from './routes/report'
import { Route as NotfoundImport } from './routes/notfound'
import { Route as NewHomeImport } from './routes/newHome'
import { Route as ModuleRegisterImport } from './routes/moduleRegister'
import { Route as ModuleImport } from './routes/module'
import { Route as HomeImport } from './routes/home'
import { Route as FarmImport } from './routes/farm'
import { Route as BitacorasImport } from './routes/bitacoras'
import { Route as BitacoraRegisterImport } from './routes/bitacoraRegister'
import { Route as AuthImport } from './routes/auth'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const UserRegisterRoute = UserRegisterImport.update({
  id: '/userRegister',
  path: '/userRegister',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const ReportRoute = ReportImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRoute,
} as any)

const NotfoundRoute = NotfoundImport.update({
  id: '/notfound',
  path: '/notfound',
  getParentRoute: () => rootRoute,
} as any)

const NewHomeRoute = NewHomeImport.update({
  id: '/newHome',
  path: '/newHome',
  getParentRoute: () => rootRoute,
} as any)

const ModuleRegisterRoute = ModuleRegisterImport.update({
  id: '/moduleRegister',
  path: '/moduleRegister',
  getParentRoute: () => rootRoute,
} as any)

const ModuleRoute = ModuleImport.update({
  id: '/module',
  path: '/module',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const FarmRoute = FarmImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRoute,
} as any)

const BitacorasRoute = BitacorasImport.update({
  id: '/bitacoras',
  path: '/bitacoras',
  getParentRoute: () => rootRoute,
} as any)

const BitacoraRegisterRoute = BitacoraRegisterImport.update({
  id: '/bitacoraRegister',
  path: '/bitacoraRegister',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/bitacoraRegister': {
      id: '/bitacoraRegister'
      path: '/bitacoraRegister'
      fullPath: '/bitacoraRegister'
      preLoaderRoute: typeof BitacoraRegisterImport
      parentRoute: typeof rootRoute
    }
    '/bitacoras': {
      id: '/bitacoras'
      path: '/bitacoras'
      fullPath: '/bitacoras'
      preLoaderRoute: typeof BitacorasImport
      parentRoute: typeof rootRoute
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/module': {
      id: '/module'
      path: '/module'
      fullPath: '/module'
      preLoaderRoute: typeof ModuleImport
      parentRoute: typeof rootRoute
    }
    '/moduleRegister': {
      id: '/moduleRegister'
      path: '/moduleRegister'
      fullPath: '/moduleRegister'
      preLoaderRoute: typeof ModuleRegisterImport
      parentRoute: typeof rootRoute
    }
    '/newHome': {
      id: '/newHome'
      path: '/newHome'
      fullPath: '/newHome'
      preLoaderRoute: typeof NewHomeImport
      parentRoute: typeof rootRoute
    }
    '/notfound': {
      id: '/notfound'
      path: '/notfound'
      fullPath: '/notfound'
      preLoaderRoute: typeof NotfoundImport
      parentRoute: typeof rootRoute
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/userRegister': {
      id: '/userRegister'
      path: '/userRegister'
      fullPath: '/userRegister'
      preLoaderRoute: typeof UserRegisterImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bitacoraRegister': typeof BitacoraRegisterRoute
  '/bitacoras': typeof BitacorasRoute
  '/farm': typeof FarmRoute
  '/home': typeof HomeRoute
  '/module': typeof ModuleRoute
  '/moduleRegister': typeof ModuleRegisterRoute
  '/newHome': typeof NewHomeRoute
  '/notfound': typeof NotfoundRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/userRegister': typeof UserRegisterRoute
  '/users': typeof UsersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bitacoraRegister': typeof BitacoraRegisterRoute
  '/bitacoras': typeof BitacorasRoute
  '/farm': typeof FarmRoute
  '/home': typeof HomeRoute
  '/module': typeof ModuleRoute
  '/moduleRegister': typeof ModuleRegisterRoute
  '/newHome': typeof NewHomeRoute
  '/notfound': typeof NotfoundRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/userRegister': typeof UserRegisterRoute
  '/users': typeof UsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bitacoraRegister': typeof BitacoraRegisterRoute
  '/bitacoras': typeof BitacorasRoute
  '/farm': typeof FarmRoute
  '/home': typeof HomeRoute
  '/module': typeof ModuleRoute
  '/moduleRegister': typeof ModuleRegisterRoute
  '/newHome': typeof NewHomeRoute
  '/notfound': typeof NotfoundRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/userRegister': typeof UserRegisterRoute
  '/users': typeof UsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bitacoraRegister'
    | '/bitacoras'
    | '/farm'
    | '/home'
    | '/module'
    | '/moduleRegister'
    | '/newHome'
    | '/notfound'
    | '/report'
    | '/reset-password'
    | '/userRegister'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bitacoraRegister'
    | '/bitacoras'
    | '/farm'
    | '/home'
    | '/module'
    | '/moduleRegister'
    | '/newHome'
    | '/notfound'
    | '/report'
    | '/reset-password'
    | '/userRegister'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/bitacoraRegister'
    | '/bitacoras'
    | '/farm'
    | '/home'
    | '/module'
    | '/moduleRegister'
    | '/newHome'
    | '/notfound'
    | '/report'
    | '/reset-password'
    | '/userRegister'
    | '/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BitacoraRegisterRoute: typeof BitacoraRegisterRoute
  BitacorasRoute: typeof BitacorasRoute
  FarmRoute: typeof FarmRoute
  HomeRoute: typeof HomeRoute
  ModuleRoute: typeof ModuleRoute
  ModuleRegisterRoute: typeof ModuleRegisterRoute
  NewHomeRoute: typeof NewHomeRoute
  NotfoundRoute: typeof NotfoundRoute
  ReportRoute: typeof ReportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UserRegisterRoute: typeof UserRegisterRoute
  UsersRoute: typeof UsersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BitacoraRegisterRoute: BitacoraRegisterRoute,
  BitacorasRoute: BitacorasRoute,
  FarmRoute: FarmRoute,
  HomeRoute: HomeRoute,
  ModuleRoute: ModuleRoute,
  ModuleRegisterRoute: ModuleRegisterRoute,
  NewHomeRoute: NewHomeRoute,
  NotfoundRoute: NotfoundRoute,
  ReportRoute: ReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UserRegisterRoute: UserRegisterRoute,
  UsersRoute: UsersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/about",
        "/auth",
        "/bitacoraRegister",
        "/bitacoras",
        "/farm",
        "/home",
        "/module",
        "/moduleRegister",
        "/newHome",
        "/notfound",
        "/report",
        "/reset-password",
        "/userRegister",
        "/users"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/about": {
      "filePath": "about.ts"
    },
    "/auth": {
      "filePath": "auth.ts"
    },
    "/bitacoraRegister": {
      "filePath": "bitacoraRegister.ts"
    },
    "/bitacoras": {
      "filePath": "bitacoras.ts"
    },
    "/farm": {
      "filePath": "farm.ts"
    },
    "/home": {
      "filePath": "home.ts"
    },
    "/module": {
      "filePath": "module.ts"
    },
    "/moduleRegister": {
      "filePath": "moduleRegister.ts"
    },
    "/newHome": {
      "filePath": "newHome.ts"
    },
    "/notfound": {
      "filePath": "notfound.ts"
    },
    "/report": {
      "filePath": "report.ts"
    },
    "/reset-password": {
      "filePath": "reset-password.ts"
    },
    "/userRegister": {
      "filePath": "userRegister.ts"
    },
    "/users": {
      "filePath": "users.ts"
    }
  }
}
ROUTE_MANIFEST_END */
